version: '3'
services:
  cozo-api:
    image: bruyland/amaron-cozo-api:latest
    container_name: cozo-api
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      LOG_FOLDER: './mylogs'
      LOG_FILE_PREFIX: './tsHA__'
      CONFIG_FOLDER: './config'
      MAIN_CONFIG_FILE: 'config.js'
#    volumes:
#      - /usr/bruyland/cozo-api/logs:/usr/bruyland/logs
#      - /usr/bruyland/cozo-api/config:/usr/bruyland/dist/config
#    ports:
#      - '2999:3000'
#      entrypoint:
#         - /bin/bash
